=== skvirel17/wine-managment-system-project-/TblManufactures.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="TblManufactures" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
<xsd:attribute name="generated" type="xsd:dateTime"/>
</xsd:complexType>
</xsd:element>
<xsd:element name="TblManufactures">
<xsd:annotation>
<xsd:appinfo>
<od:index index-name="PrimaryKey" index-key="manufactureId " primary="yes" unique="yes" clustered="no" order="asc"/>
<od:tableProperty name="PublishToWeb" type="2" value="1"/>
<od:tableProperty name="Orientation" type="2" value="0"/>
<od:tableProperty name="OrderByOn" type="1" value="0"/>
<od:tableProperty name="NameMap" type="11" value="CswOVQAAAACkts5T8vJBRo8BVagQ8A/sAAAAACyNwFf2SeZAAAAAAAAAAABUAGIA
bABNAGEAbgB1AGYAYQBjAHQAdQByAGUAcwAAAAAAAADF+ecWy/ZhR5YnUnOdR5GA
AAAAAAA5OVz2SeZAAAAAAAAAAABUAGIAbABXAGkAbgBlAHMAAAAAAAAA5tldhf2t
G0e2WEaLNp5VrgcAAACkts5T8vJBRo8BVagQ8A/sbQBhAG4AdQBmAGEAYwB0AHUA
cgBlAEkAZAAAAAAAAAD/B/ihwP0IRq1uFKO7+pJ4BwAAAKS2zlPy8kFGjwFVqBDw
D+xtAGEAbgB1AGYAYQBjAHQAdQByAGUARgB1AGwAbABOAGEAbQBlAAAAAAAAAGo/
RO1DdJ5FoQmgLACx/S8HAAAApLbOU/LyQUaPAVWoEPAP7G0AYQBuAHUAZgBhAGMA
dAB1AHIAZQBQAGgAbwBuAGUATgB1AG0AYgBlAHIAAAAAAAAAS6npQhcIWEacSjr6
bpC6MgcAAACkts5T8vJBRo8BVagQ8A/sbQBhAG4AdQBmAGEAYwB0AHUAcgBlAEEA
ZABkAHIAZQBzAHMAQwBpAHQAeQAAAAAAAAAq9OoLSoyLToEMiWbR0v3HBwAAAKS2
zlPy8kFGjwFVqBDwD+xtAGEAbgB1AGYAYQBjAHQAdQByAGUAQQBkAGQAcgBlAHMA
cwBTAHQAcgBlAGUAdAAAAAAAAADa4CnWbOM0QL5xvC4uqyk/BwAAAKS2zlPy8kFG
jwFVqBDwD+xtAGEAbgB1AGYAYQBjAHQAdQByAGUAQQBkAGQAcgBlAHMAcwBCAHUA
bABkAGkAbgBnAAAAAAAAAFNZ2MB+5g9LlxmmOJroA5UHAAAApLbOU/LyQUaPAVWo
EPAP7G0AYQBuAHUAZgBhAGMAdAB1AHIAZQBFAG0AYQBpAGwAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAwAAAAFAAAAAAAAAAAAAAAAAAAAAAA=
"/>
<od:tableProperty name="DefaultView" type="2" value="2"/>
<od:tableProperty name="GUID" type="9" value="pLbOU/LyQUaPAVWoEPAP7A==
"/>
<od:tableProperty name="DisplayViewsOnSharePointSite" type="2" value="1"/>
<od:tableProperty name="TotalsRow" type="1" value="0"/>
<od:tableProperty name="FilterOnLoad" type="1" value="0"/>
<od:tableProperty name="OrderByOnLoad" type="1" value="1"/>
<od:tableProperty name="HideNewField" type="1" value="0"/>
<od:tableProperty name="BackTint" type="6" value="100"/>
<od:tableProperty name="BackShade" type="6" value="100"/>
<od:tableProperty name="ThemeFontIndex" type="4" value="1"/>
<od:tableProperty name="AlternateBackThemeColorIndex" type="4" value="1"/>
<od:tableProperty name="AlternateBackTint" type="6" value="100"/>
<od:tableProperty name="AlternateBackShade" type="6" value="95"/>
<od:tableProperty name="ReadOnlyWhenDisconnected" type="1" value="0"/>
<od:tableProperty name="DatasheetGridlinesThemeColorIndex" type="4" value="3"/>
<od:tableProperty name="DatasheetForeThemeColorIndex" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="manufactureId" minOccurs="1" od:jetType="longinteger" od:sqlSType="int" od:nonNullable="yes" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="5tldhf2tG0e2WEaLNp5Vrg==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="1"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="DefaultValue" type="12" value="0"/>
<od:fieldProperty name="Required" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="manufactureFullName" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="/wf4ocD9CEatbhSju/qSeA==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="2424"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="manufacturePhoneNumber" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="aj9E7UN0nkWhCaAsALH9Lw==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="1992"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="DefaultValue" type="12" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="manufactureAddressCity" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="S6npQhcIWEacSjr6bpC6Mg==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="2208"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="manufactureAddressStreet" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="KvTqC0qMi06BDIlm0dL9xw==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="2352"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="manufactureAddressBulding" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="2uAp1mzjNEC+cbwuLqspPw==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="2340"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="DefaultValue" type="12" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="manufactureEmail" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="U1nYwH7mD0uXGaY4mugDlQ==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="4620"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== skvirel17/wine-managment-system-project-/TblManufactures.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="TblManufactures.xsd" generated="2025-01-12T12:31:03">
<TblManufactures>
<manufactureId>501</manufactureId>
<manufactureFullName>Netanya Foods</manufactureFullName>
<manufacturePhoneNumber>525678901</manufacturePhoneNumber>
<manufactureAddressCity>Netanya</manufactureAddressCity>
<manufactureAddressStreet>Herzog</manufactureAddressStreet>
<manufactureAddressBulding>15</manufactureAddressBulding>
<manufactureEmail>orders@netanyafoods.com</manufactureEmail>
</TblManufactures>
<TblManufactures>
<manufactureId>502</manufactureId>
<manufactureFullName>Ramat Gan Plastics</manufactureFullName>
<manufacturePhoneNumber>526789012</manufacturePhoneNumber>
<manufactureAddressCity>Ramat Gan</manufactureAddressCity>
<manufactureAddressStreet>Herzog</manufactureAddressStreet>
<manufactureAddressBulding>16</manufactureAddressBulding>
<manufactureEmail>plastics@ramatganplastics.com</manufactureEmail>
</TblManufactures>
<TblManufactures>
<manufactureId>503</manufactureId>
<manufactureFullName>Beer Sheva Metals</manufactureFullName>
<manufacturePhoneNumber>529012345</manufacturePhoneNumber>
<manufactureAddressCity>Beer Sheva</manufactureAddressCity>
<manufactureAddressStreet>Shalom</manufactureAddressStreet>
<manufactureAddressBulding>19</manufactureAddressBulding>
<manufactureEmail>contact@bsmetals.com</manufactureEmail>
</TblManufactures>
<TblManufactures>
<manufactureId>504</manufactureId>
<manufactureFullName>Haifa Chemicals</manufactureFullName>
<manufacturePhoneNumber>521234568</manufacturePhoneNumber>
<manufactureAddressCity>Haifa</manufactureAddressCity>
<manufactureAddressStreet>Gordon</manufactureAddressStreet>
<manufactureAddressBulding>30</manufactureAddressBulding>
<manufactureEmail>chemicals@haifachem.com</manufactureEmail>
</TblManufactures>
<TblManufactures>
<manufactureId>505</manufactureId>
<manufactureFullName>Ramat Gan Steel</manufactureFullName>
<manufacturePhoneNumber>529012346</manufacturePhoneNumber>
<manufactureAddressCity>Ramat Gan</manufactureAddressCity>
<manufactureAddressStreet>Levona</manufactureAddressStreet>
<manufactureAddressBulding>29</manufactureAddressBulding>
<manufactureEmail>steel@rgsteel.com</manufactureEmail>
</TblManufactures>
<TblManufactures>
<manufactureId>506</manufactureId>
<manufactureFullName>Tel Aviv Apparel</manufactureFullName>
<manufacturePhoneNumber>522345679</manufacturePhoneNumber>
<manufactureAddressCity>Tel Aviv</manufactureAddressCity>
<manufactureAddressStreet>Ben Gurion</manufactureAddressStreet>
<manufactureAddressBulding>31</manufactureAddressBulding>
<manufactureEmail>apparel@telapparel.com</manufactureEmail>
</TblManufactures>
<TblManufactures>
<manufactureId>507</manufactureId>
<manufactureFullName>Kiryat Shmona Produce</manufactureFullName>
<manufacturePhoneNumber>528901235</manufacturePhoneNumber>
<manufactureAddressCity>Kiryat Shmona</manufactureAddressCity>
<manufactureAddressStreet>Shalom</manufactureAddressStreet>
<manufactureAddressBulding>28</manufactureAddressBulding>
<manufactureEmail>produce@ksp.com</manufactureEmail>
</TblManufactures>
<TblManufactures>
<manufactureId>508</manufactureId>
<manufactureFullName>Tel Aviv Logistics</manufactureFullName>
<manufacturePhoneNumber>524567891</manufacturePhoneNumber>
<manufactureAddressCity>Tel Aviv</manufactureAddressCity>
<manufactureAddressStreet>Herzog</manufactureAddressStreet>
<manufactureAddressBulding>24</manufactureAddressBulding>
<manufactureEmail>logistics@tavalogistics.com</manufactureEmail>
</TblManufactures>
<TblManufactures>
<manufactureId>509</manufactureId>
<manufactureFullName>Haifa Motors</manufactureFullName>
<manufacturePhoneNumber>522345678</manufacturePhoneNumber>
<manufactureAddressCity>Haifa</manufactureAddressCity>
<manufactureAddressStreet>Ben Gurion</manufactureAddressStreet>
<manufactureAddressBulding>12</manufactureAddressBulding>
<manufactureEmail>contact@haifamotors.com</manufactureEmail>
</TblManufactures>
<TblManufactures>
<manufactureId>510</manufactureId>
<manufactureFullName>Tel Aviv Electronics</manufactureFullName>
<manufacturePhoneNumber>521234567</manufacturePhoneNumber>
<manufactureAddressCity>Tel Aviv</manufactureAddressCity>
<manufactureAddressStreet>Rothschild</manufactureAddressStreet>
<manufactureAddressBulding>11</manufactureAddressBulding>
<manufactureEmail>info@taelectronics.com</manufactureEmail>
</TblManufactures>
<TblManufactures>
<manufactureId>511</manufactureId>
<manufactureFullName>Netanya Pharma</manufactureFullName>
<manufacturePhoneNumber>525678902</manufacturePhoneNumber>
<manufactureAddressCity>Netanya</manufactureAddressCity>
<manufactureAddressStreet>Jabotinsky</manufactureAddressStreet>
<manufactureAddressBulding>25</manufactureAddressBulding>
<manufactureEmail>pharma@netanyapharma.com</manufactureEmail>
</TblManufactures>
<TblManufactures>
<manufactureId>512</manufactureId>
<manufactureFullName>Jerusalem Textiles</manufactureFullName>
<manufacturePhoneNumber>524567890</manufacturePhoneNumber>
<manufactureAddressCity>Jerusalem</manufactureAddressCity>
<manufactureAddressStreet>King George</manufactureAddressStreet>
<manufactureAddressBulding>14</manufactureAddressBulding>
<manufactureEmail>support@jertextiles.com</manufactureEmail>
</TblManufactures>
<TblManufactures>
<manufactureId>513</manufactureId>
<manufactureFullName>Modiin Chemicals</manufactureFullName>
<manufacturePhoneNumber>527890123</manufacturePhoneNumber>
<manufactureAddressCity>Modiin</manufactureAddressCity>
<manufactureAddressStreet>Ben Gurion</manufactureAddressStreet>
<manufactureAddressBulding>17</manufactureAddressBulding>
<manufactureEmail>info@modiinchem.com</manufactureEmail>
</TblManufactures>
<TblManufactures>
<manufactureId>514</manufactureId>
<manufactureFullName>Ashdod Furniture</manufactureFullName>
<manufacturePhoneNumber>523456789</manufacturePhoneNumber>
<manufactureAddressCity>Ashdod</manufactureAddressCity>
<manufactureAddressStreet>Shalom</manufactureAddressStreet>
<manufactureAddressBulding>13</manufactureAddressBulding>
<manufactureEmail>sales@ashdodfurniture.com</manufactureEmail>
</TblManufactures>
<TblManufactures>
<manufactureId>515</manufactureId>
<manufactureFullName>Ashdod Electronics</manufactureFullName>
<manufacturePhoneNumber>526789013</manufacturePhoneNumber>
<manufactureAddressCity>Ashdod</manufactureAddressCity>
<manufactureAddressStreet>Shapira</manufactureAddressStreet>
<manufactureAddressBulding>26</manufactureAddressBulding>
<manufactureEmail>electronics@ashelectronics.com</manufactureEmail>
</TblManufactures>
<TblManufactures>
<manufactureId>516</manufactureId>
<manufactureFullName>Haifa Shipping</manufactureFullName>
<manufacturePhoneNumber>523456790</manufacturePhoneNumber>
<manufactureAddressCity>Haifa</manufactureAddressCity>
<manufactureAddressStreet>Levona</manufactureAddressStreet>
<manufactureAddressBulding>23</manufactureAddressBulding>
<manufactureEmail>shipping@haifashipping.com</manufactureEmail>
</TblManufactures>
<TblManufactures>
<manufactureId>517</manufactureId>
<manufactureFullName>Petah Tikva Machinery</manufactureFullName>
<manufacturePhoneNumber>528901234</manufacturePhoneNumber>
<manufactureAddressCity>Petah Tikva</manufactureAddressCity>
<manufactureAddressStreet>Haim</manufactureAddressStreet>
<manufactureAddressBulding>18</manufactureAddressBulding>
<manufactureEmail>machinery@petmachinery.com</manufactureEmail>
</TblManufactures>
<TblManufactures>
<manufactureId>518</manufactureId>
<manufactureFullName>Netanya Construction</manufactureFullName>
<manufacturePhoneNumber>523456780</manufacturePhoneNumber>
<manufactureAddressCity>Netanya</manufactureAddressCity>
<manufactureAddressStreet>Herzog</manufactureAddressStreet>
<manufactureAddressBulding>32</manufactureAddressBulding>
<manufactureEmail>construction@netanyacon.com</manufactureEmail>
</TblManufactures>
<TblManufactures>
<manufactureId>519</manufactureId>
<manufactureFullName>Rishon Lezion Wines</manufactureFullName>
<manufacturePhoneNumber>520123456</manufacturePhoneNumber>
<manufactureAddressCity>Rishon Lezion</manufactureAddressCity>
<manufactureAddressStreet>Shapira</manufactureAddressStreet>
<manufactureAddressBulding>20</manufactureAddressBulding>
<manufactureEmail>wines@rishonwines.com</manufactureEmail>
</TblManufactures>
<TblManufactures>
<manufactureId>520</manufactureId>
<manufactureFullName>Modiin Furniture</manufactureFullName>
<manufacturePhoneNumber>527890124</manufacturePhoneNumber>
<manufactureAddressCity>Modiin</manufactureAddressCity>
<manufactureAddressStreet>Ayalon</manufactureAddressStreet>
<manufactureAddressBulding>27</manufactureAddressBulding>
<manufactureEmail>furniture@modiinfurn.com</manufactureEmail>
</TblManufactures>
</dataroot>
